name: C++ code checker using cppcheck
description: Automatically checks your repository with cppcheck.
author: Gregor Seljak
branding:
  icon: alert-circle
  color: green
runs:
  using: "docker"
  image: "Dockerfile"
